name: Build Kernel and Release

on:
  push:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      DATE: ${{ steps.setdate.outputs.DATE }}
    steps:
      - id: setdate
        run: |
          echo "DATE=$(TZ=Asia/Jakarta date +%Y%m%d%H%M)" >> $GITHUB_OUTPUT

  build_kernel:
    name: Build Kernel and Release
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      matrix:
        include:
          - variant: "staging"
            root: "KSU"
          - variant: "staging"
            root: "NoKSU"

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Set environment
      run: |
        echo "VARIANT=${{ matrix.variant }}" >> $GITHUB_ENV
        echo "ROOT=${{ matrix.root }}" >> $GITHUB_ENV
        echo "DATE=${{ needs.prepare.outputs.DATE }}" >> $GITHUB_ENV
        echo "ARTIFACT=$GITHUB_WORKSPACE/artifact" >> $GITHUB_ENV

    - name: Building
      run: |
        sudo apt install device-tree-compiler -y
        mkdir -p ${{ env.ARTIFACT }}
        chmod +x build.sh && ./build.sh ${{ env.ROOT }} ${{ env.DATE }} ${{ env.ARTIFACT }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: rethinking-${{ env.VARIANT }}-${{ env.ROOT }}-${{ env.DATE }}
        path: ${{ env.ARTIFACT }}/*

  create_release:
    needs: [prepare, build_kernel]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup git authentication
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/Cilok-LAB/android_kernel_xiaomi_surya

      - name: Set DATE and TAG
        run: |
          echo "TAG=${{ needs.prepare.outputs.DATE }}" >> $GITHUB_ENV

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifact

      - name: Create Git tag
        run: |
          git tag -a "$TAG" -m "ilysm tirr"
          git push origin "$TAG"

      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          files: artifact/**
          body: |
            Device Target: POCO X3 NFC (surya)
            Kernel Source: https://github.com/Cilok-LAB/android_kernel_xiaomi_surya.git
            Kernel Version: 4.14.357
            Clang Version: AOSP Clang v21.0.0

            ### Changelog:
            - https://github.com/Cilok-LAB/android_kernel_xiaomi_surya/commits/rethinking

            ### Notes
            *Flash carefully. Do not interrupt the synchronization.*
            *MIUI/HyperOS and AOSP/A support*
            *Android 11-17 support*

            ### Flash this module if you using ksu variant:
            - https://github.com/backslashxx/mountify/releases/tag/203

            ### Recommend Manager (Choose one!):
            - Official KernelSU: https://t.me/CilokG05/492
            - KernelSU-Next: https://t.me/CilokG05/489
            - xxKernelSU: https://t.me/CilokG05/491
            - KowSU: https://t.me/CilokG05/493
            - MamboSU: https://t.me/CilokG05/494
            - Wild KSU: https://t.me/CilokG05/497
            - Rsuntk KSU: https://t.me/CilokG05/490
            - ReSukiSU: https://t.me/CilokG05/495
            - SukiSU-Ultra: https://t.me/CilokG05/496
